version: '2'
services:
  GMAN:
    image: dockermatrix123/matrix:matrix
    container_name: matrix
    ports:
      - 8568:8568
    stdin_open: true
    tty: true
    networks:
      extnetwork:
        ipv4_address: 10.0.75.2
  EXP:
    image: dockermatrix123/matrix:man
    container_name: explore
    privileged: true
    environment:
      IP: 10.0.75.2
    ports:
      - 3000:3000
      - 8011:80
    depends_on:
      - GMAN
    stdin_open: true
    tty: true
    networks:
      extnetwork:
        ipv4_address: 10.0.75.3
networks:
  extnetwork:
    ipam:
      config:
      - subnet: 10.0.75.0/24
        gateway: 10.0.75.1